apiVersion: apps/v1
kind: Deployment
metadata:
  name: omzetter
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: omzetter
  template:
    metadata:
      labels:
        app: omzetter
    spec:
      containers:
        - name: omzetter
          image: omzetter:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: omzetter-balancer
spec:
  selector:
    app: omzetter
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
